Fix docs (#54)
* Restrict permissions on generated ssh key

I received the following error when trying to ssh into my test guest:

$ ssh -i ~/.ssh/id_rsa_cloud ubuntu@10.228.68.21
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: UNPROTECTED PRIVATE KEY FILE! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/home/ubuntu/.ssh/id_rsa_cloud' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/home/ubuntu/.ssh/id_rsa_cloud": bad permissions
Permission denied (publickey).

This is because my umask settings create new files with 0644 bits by
default. Let's create the file in advance with appropriate permissions
before writing a private key to it. LP: #1736795.

* Use openstack client to create/assign floating ips

The docs instruct the user to run 'nova floating-ip-create', which is not
a valid command (see below). Use the openstack client instead. LP: #1736795.

$ nova floating-ip-create
usage: nova [--version] [--debug] [--os-cache] [--timings]
            [--os-region-name <region-name>] [--service-type <service-type>]
            [--service-name <service-name>]
            [--os-endpoint-type <endpoint-type>]
            [--os-compute-api-version <compute-api-ver>]
            [--endpoint-override <bypass-url>] [--insecure]
            [--os-cacert <ca-certificate>] [--os-cert <certificate>]
            [--os-key <key>] [--timeout <seconds>] [--os-auth-type <name>]
            [--os-auth-url OS_AUTH_URL] [--os-domain-id OS_DOMAIN_ID]
            [--os-domain-name OS_DOMAIN_NAME] [--os-project-id OS_PROJECT_ID]
            [--os-project-name OS_PROJECT_NAME]
            [--os-project-domain-id OS_PROJECT_DOMAIN_ID]
            [--os-project-domain-name OS_PROJECT_DOMAIN_NAME]
            [--os-trust-id OS_TRUST_ID]
            [--os-default-domain-id OS_DEFAULT_DOMAIN_ID]
            [--os-default-domain-name OS_DEFAULT_DOMAIN_NAME]
            [--os-user-id OS_USER_ID] [--os-username OS_USERNAME]
            [--os-user-domain-id OS_USER_DOMAIN_ID]
            [--os-user-domain-name OS_USER_DOMAIN_NAME]
            [--os-password OS_PASSWORD]
            <subcommand> ...
error: argument <subcommand>: invalid choice: u'floating-ip-create'
Try 'nova help ' for more information.

* Clarify security group instructions

It isn't obvious what the pronoun "this" isn referring to - is it just the
first step or all the steps? Clarify that we intended the latter.

Also, fix typo 's/todo/to do/'. LP: #1736795.

* Fix security group rule instructions to avoid nonspecific security_group error

Following along in the "Accessing your instance" section, I received errors
about having multiple security groups with the name "default". See below.
And, alas, I was unable to ssh into my guest after executing them.

I discovered that if I re-ran those commands, using the UUID of the first
security group in the list, they then succeeded and I could ssh in.
Replace the instructions with the process I used. While my process
is probably sub-optimal (requires more from the user than a cut & paste),
it at least works :) LP: #1736795.

$ neutron security-group-rule-create --protocol icmp \
> --direction ingress default
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Multiple security_group matches found for name 'default', use an ID to be more specific.
$ neutron security-group-rule-create --protocol tcp \
> --port-range-min 22 --port-range-max 22 \
> --direction ingress default
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Multiple security_group matches found for name 'default', use an ID to be more specific.